# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "librarian"
license = "MIT"
licenselink = "https://github.com/nukosuke/hugo-librarian/blob/master/LICENSE"
description = "Hugo theme powered by Bulma and Stimulus"
homepage = "https://nukosuke.github.io/hugo-librarian-demo/"
tags = ["bulma", "turbolinks", "stimulus", "typescript", "webpack"]
features = []
min_version = "0.57"

[author]
  name = "nukosuke"
  homepage = "https://www.nukosuke.com"
